### ISSUE TITLE
ROS system setup

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/PlantMap3D-ROS#1]

**Comment by mtfunder** [comment]
@marialauracangiano is this supposed to be here?

**Comment by marialauracangiano** [comment]
Nop, this is from before we had a ROS dedicated repo. I'll move it.

**Comment by MathewAaron** [comment]
Waiting for display cables to start setting up the Jetson. Have the necessary resources ready.

**Comment by mtfunder** [comment]
Display cables are on order, possible arrival tomorrow but more likely Monday / Tuesday.

**Comment by MathewAaron** [comment]
ROS setup completed.
