### ISSUE TITLE
Expand camera-trigger msg to include metadata (lat,lon, heading,gps-time)

### ISSUE THREAD

**Issue by skovsens** [precision-sustainable-ag/PlantMap3D-ROS#24]
You need to expand the camera-trigger msg to include the metadata in the title. lat,lon and gps-time need to be the current/most recent values, that is directly accessible from the cpp-file. You can rely on the lastnorthing and lasteasting for calculating the heading. This is the location of the most recently captured image, corresponding to the tractor location about 1 second back in time. Remember to put some identifier in case lastnorthing and lasteasting is uninitiazlied (aka the first image captured in a run). 
If you'd like, you can add this identifier as something like a heading of -1, fx.

**Comment by MathewAaron** [comment]
Done.
