### ISSUE TITLE
Uploading dummy scripts into each driver folder

### ISSUE THREAD

**Issue by danielginn** [precision-sustainable-ag/PlantMap3D-ROS#5]
Need to upload dummy scripts that will receive the correct inputs and will create dummy data for returning the correct outputs. Upload to the setup/ros_drivers branch
- [x] biomass_estimator_driver @danielginn 
- [x] biomass_map_driver @priyajakhar 
- [x] gps_module_driver @MathewAaron 
- [x] camera_trigger_driver @skovsens 
- [x] height_map_driver @danielginn 
- [x] oakd_camera_driver (rgb image, depth map image, segmentation image) @MathewAaron @Djyankencsu 
- [x] height_sensor_driver @MathewAaron

**Comment by MathewAaron** [comment]
Currently testing camera trigger and camera data publishing. This should help me test the biomass estimation pipeline this week.
